const drivers = [{
		"Name": "Baby-Peach",
		"Speed G": 0,
		"Speed W": 0,
		"Speed A": 0,
		"Speed AG": 0,
		"Acceleration": 4,
		"Weight": 0,
		"Handling G": 10,
		"Handling W": 10,
		"Handling A": 10,
		"Handling AG": 10,
		"Traction": 5,
		"Mini-Turbo": 5
	},
	{
		"Name": "Lemmy",
		"Speed G": 0,
		"Speed W": 0,
		"Speed A": 0,
		"Speed AG": 0,
		"Acceleration": 5,
		"Weight": 0,
		"Handling G": 9,
		"Handling W": 9,
		"Handling A": 9,
		"Handling AG": 9,
		"Traction": 3,
		"Mini-Turbo": 5
	},
	{
		"Name": "Dry-Bones",
		"Speed G": 1,
		"Speed W": 1,
		"Speed A": 1,
		"Speed AG": 1,
		"Acceleration": 5,
		"Weight": 1,
		"Handling G": 8,
		"Handling W": 8,
		"Handling A": 8,
		"Handling AG": 8,
		"Traction": 4,
		"Mini-Turbo": 4
	},
	{
		"Name": "Toadette",
		"Speed G": 2,
		"Speed W": 2,
		"Speed A": 2,
		"Speed AG": 2,
		"Acceleration": 5,
		"Weight": 2,
		"Handling G": 7,
		"Handling W": 7,
		"Handling A": 7,
		"Handling AG": 7,
		"Traction": 2,
		"Mini-Turbo": 4
	},
	{
		"Name": "Koopa",
		"Speed G": 2,
		"Speed W": 2,
		"Speed A": 2,
		"Speed AG": 2,
		"Acceleration": 4,
		"Weight": 2,
		"Handling G": 8,
		"Handling W": 8,
		"Handling A": 8,
		"Handling AG": 8,
		"Traction": 5,
		"Mini-Turbo": 4
	},
	{
		"Name": "Toad",
		"Speed G": 3,
		"Speed W": 3,
		"Speed A": 3,
		"Speed AG": 3,
		"Acceleration": 4,
		"Weight": 3,
		"Handling G": 7,
		"Handling W": 7,
		"Handling A": 7,
		"Handling AG": 7,
		"Traction": 4,
		"Mini-Turbo": 3
	},
	{
		"Name": "Inkling-Girl",
		"Speed G": 4,
		"Speed W": 4,
		"Speed A": 4,
		"Speed AG": 4,
		"Acceleration": 4,
		"Weight": 3,
		"Handling G": 6,
		"Handling W": 6,
		"Handling A": 6,
		"Handling AG": 6,
		"Traction": 3,
		"Mini-Turbo": 3
	},
	{
		"Name": "Peach",
		"Speed G": 5,
		"Speed W": 5,
		"Speed A": 5,
		"Speed AG": 5,
		"Acceleration": 3,
		"Weight": 4,
		"Handling G": 5,
		"Handling W": 5,
		"Handling A": 5,
		"Handling AG": 5,
		"Traction": 3,
		"Mini-Turbo": 3
	},
	{
		"Name": "Inkling-Boy",
		"Speed G": 5,
		"Speed W": 5,
		"Speed A": 5,
		"Speed AG": 5,
		"Acceleration": 3,
		"Weight": 5,
		"Handling G": 5,
		"Handling W": 5,
		"Handling A": 5,
		"Handling AG": 5,
		"Traction": 1,
		"Mini-Turbo": 3
	},
	{
		"Name": "Mario",
		"Speed G": 6,
		"Speed W": 6,
		"Speed A": 6,
		"Speed AG": 6,
		"Acceleration": 2,
		"Weight": 6,
		"Handling G": 4,
		"Handling W": 4,
		"Handling A": 4,
		"Handling AG": 4,
		"Traction": 2,
		"Mini-Turbo": 2
	},
	{
		"Name": "Luigi",
		"Speed G": 6,
		"Speed W": 6,
		"Speed A": 6,
		"Speed AG": 6,
		"Acceleration": 2,
		"Weight": 6,
		"Handling G": 5,
		"Handling W": 5,
		"Handling A": 5,
		"Handling AG": 5,
		"Traction": 1,
		"Mini-Turbo": 2
	},
	{
		"Name": "Metal-Mario",
		"Speed G": 8,
		"Speed W": 8,
		"Speed A": 8,
		"Speed AG": 8,
		"Acceleration": 1,
		"Weight": 10,
		"Handling G": 3,
		"Handling W": 3,
		"Handling A": 3,
		"Handling AG": 3,
		"Traction": 1,
		"Mini-Turbo": 1
	},
	{
		"Name": "Boo",
		"Speed G": 7,
		"Speed W": 7,
		"Speed A": 7,
		"Speed AG": 7,
		"Acceleration": 1,
		"Weight": 7,
		"Handling G": 3,
		"Handling W": 3,
		"Handling A": 3,
		"Handling AG": 3,
		"Traction": 3,
		"Mini-Turbo": 2
	},
	{
		"Name": "Donkey-Kong",
		"Speed G": 9,
		"Speed W": 9,
		"Speed A": 9,
		"Speed AG": 9,
		"Acceleration": 1,
		"Weight": 8,
		"Handling G": 2,
		"Handling W": 2,
		"Handling A": 2,
		"Handling AG": 2,
		"Traction": 0,
		"Mini-Turbo": 1
	},
	{
		"Name": "Wario",
		"Speed G": 10,
		"Speed W": 10,
		"Speed A": 10,
		"Speed AG": 10,
		"Acceleration": 0,
		"Weight": 9,
		"Handling G": 1,
		"Handling W": 1,
		"Handling A": 1,
		"Handling AG": 1,
		"Traction": 1,
		"Mini-Turbo": 0
	},
	{
		"Name": "Bowser",
		"Speed G": 10,
		"Speed W": 10,
		"Speed A": 10,
		"Speed AG": 10,
		"Acceleration": 0,
		"Weight": 10,
		"Handling G": 0,
		"Handling W": 0,
		"Handling A": 0,
		"Handling AG": 0,
		"Traction": 0,
		"Mini-Turbo": 0
	}
];

const bodies = [{
		"Name": "Standard Kart",
		"Speed G": 3,
		"Speed W": 3,
		"Speed A": 3,
		"Speed AG": 3,
		"Acceleration": 4,
		"Weight": 2,
		"Handling G": 3,
		"Handling W": 2,
		"Handling A": 3,
		"Handling AG": 3,
		"Traction": 3,
		"Mini-Turbo": 4,
		"Inside Drift": false
	},
	{
		"Name": "Varmit",
		"Speed G": 1,
		"Speed W": 3,
		"Speed A": 1,
		"Speed AG": 1,
		"Acceleration": 6,
		"Weight": 1,
		"Handling G": 5,
		"Handling W": 4,
		"Handling A": 2,
		"Handling AG": 4,
		"Traction": 4,
		"Mini-Turbo": 6,
		"Inside Drift": false
	},
	{
		"Name": "Mach 8",
		"Speed G": 3,
		"Speed W": 3,
		"Speed A": 4,
		"Speed AG": 5,
		"Acceleration": 3,
		"Weight": 3,
		"Handling G": 2,
		"Handling W": 2,
		"Handling A": 2,
		"Handling AG": 4,
		"Traction": 4,
		"Mini-Turbo": 4,
		"Inside Drift": false
	},
	{
		"Name": "Steel Diver",
		"Speed G": 4,
		"Speed W": 5,
		"Speed A": 0,
		"Speed AG": 2,
		"Acceleration": 1,
		"Weight": 4,
		"Handling G": 1,
		"Handling W": 5,
		"Handling A": 1,
		"Handling AG": 1,
		"Traction": 3,
		"Mini-Turbo": 2,
		"Inside Drift": false
	},
	{
		"Name": "Comet",
		"Speed G": 2,
		"Speed W": 2,
		"Speed A": 4,
		"Speed AG": 3,
		"Acceleration": 5,
		"Weight": 2,
		"Handling G": 4,
		"Handling W": 2,
		"Handling A": 4,
		"Handling AG": 3,
		"Traction": 3,
		"Mini-Turbo": 5,
		"Inside Drift": true
	},
	{
		"Name": "Teddy Buggy",
		"Speed G": 2,
		"Speed W": 2,
		"Speed A": 4,
		"Speed AG": 3,
		"Acceleration": 5,
		"Weight": 2,
		"Handling G": 4,
		"Handling W": 2,
		"Handling A": 4,
		"Handling AG": 3,
		"Traction": 3,
		"Mini-Turbo": 5,
		"Inside Drift": false
	},
	{
		"Name": "Circuit Special",
		"Speed G": 5,
		"Speed W": 1,
		"Speed A": 2,
		"Speed AG": 4,
		"Acceleration": 1,
		"Weight": 3,
		"Handling G": 1,
		"Handling W": 1,
		"Handling A": 0,
		"Handling AG": 2,
		"Traction": 1,
		"Mini-Turbo": 1,
		"Inside Drift": false
	},
	{
		"Name": "Standard ATV",
		"Speed G": 5,
		"Speed W": 2,
		"Speed A": 1,
		"Speed AG": 3,
		"Acceleration": 0,
		"Weight": 4,
		"Handling G": 0,
		"Handling W": 1,
		"Handling A": 0,
		"Handling AG": 1,
		"Traction": 5,
		"Mini-Turbo": 0,
		"Inside Drift": false
	},
	{
		"Name": "Jet Bike",
		"Speed G": 4,
		"Speed W": 3,
		"Speed A": 3,
		"Speed AG": 3,
		"Acceleration": 2,
		"Weight": 1,
		"Handling G": 3,
		"Handling W": 3,
		"Handling A": 3,
		"Handling AG": 2,
		"Traction": 2,
		"Mini-Turbo": 3,
		"Inside Drift": true
	},
	{
		"Name": "Prancer",
		"Speed G": 4,
		"Speed W": 3,
		"Speed A": 3,
		"Speed AG": 3,
		"Acceleration": 2,
		"Weight": 1,
		"Handling G": 3,
		"Handling W": 3,
		"Handling A": 3,
		"Handling AG": 2,
		"Traction": 2,
		"Mini-Turbo": 3,
		"Inside Drift": false
	},
	{
		"Name": "Mr. Scooty",
		"Speed G": 0,
		"Speed W": 1,
		"Speed A": 1,
		"Speed AG": 2,
		"Acceleration": 7,
		"Weight": 0,
		"Handling G": 5,
		"Handling W": 4,
		"Handling A": 4,
		"Handling AG": 5,
		"Traction": 4,
		"Mini-Turbo": 7,
		"Inside Drift": false
	},
	{
		"Name": "Streetle",
		"Speed G": 1,
		"Speed W": 5,
		"Speed A": 2,
		"Speed AG": 0,
		"Acceleration": 6,
		"Weight": 0,
		"Handling G": 4,
		"Handling W": 5,
		"Handling A": 3,
		"Handling AG": 2,
		"Traction": 6,
		"Mini-Turbo": 6,
		"Inside Drift": false
	},
	{
		"Name": "Master Cycle",
		"Speed G": 4,
		"Speed W": 2,
		"Speed A": 3,
		"Speed AG": 3,
		"Acceleration": 2,
		"Weight": 2,
		"Handling G": 3,
		"Handling W": 2,
		"Handling A": 2,
		"Handling AG": 3,
		"Traction": 0,
		"Mini-Turbo": 3,
		"Inside Drift": true
	},
	{
		"Name": "Sneeker",
		"Speed G": 4,
		"Speed W": 2,
		"Speed A": 3,
		"Speed AG": 3,
		"Acceleration": 2,
		"Weight": 2,
		"Handling G": 3,
		"Handling W": 2,
		"Handling A": 2,
		"Handling AG": 3,
		"Traction": 0,
		"Mini-Turbo": 3,
		"Inside Drift": false
	},
	{
		"Name": "Standard Bike",
		"Speed G": 2,
		"Speed W": 2,
		"Speed A": 3,
		"Speed AG": 4,
		"Acceleration": 5,
		"Weight": 1,
		"Handling G": 4,
		"Handling W": 3,
		"Handling A": 3,
		"Handling AG": 4,
		"Traction": 5,
		"Mini-Turbo": 5,
		"Inside Drift": false
	},
	{
		"Name": "Splat Buggy",
		"Speed G": 4,
		"Speed W": 2,
		"Speed A": 3,
		"Speed AG": 4,
		"Acceleration": 3,
		"Weight": 0,
		"Handling G": 2,
		"Handling W": 3,
		"Handling A": 1,
		"Handling AG": 5,
		"Traction": 3,
		"Mini-Turbo": 3,
		"Inside Drift": false
	},
	{
		"Name": "Master Cycle Zero",
		"Speed G": 2,
		"Speed W": 4,
		"Speed A": 3,
		"Speed AG": 3,
		"Acceleration": 2,
		"Weight": 3,
		"Handling G": 4,
		"Handling W": 4,
		"Handling A": 3,
		"Handling AG": 3,
		"Traction": 7,
		"Mini-Turbo": 3,
		"Inside Drift": false
	}
];

const tires = [{
		"Name": "Standard Tires",
		"Speed G": 2,
		"Speed W": 3,
		"Speed A": 3,
		"Speed AG": 2,
		"Acceleration": 4,
		"Weight": 2,
		"Handling G": 3,
		"Handling W": 3,
		"Handling A": 3,
		"Handling AG": 3,
		"Traction": 5,
		"Mini-Turbo": 3
	},
	{
		"Name": "Monster",
		"Speed G": 2,
		"Speed W": 2,
		"Speed A": 1,
		"Speed AG": 2,
		"Acceleration": 2,
		"Weight": 4,
		"Handling G": 0,
		"Handling W": 1,
		"Handling A": 1,
		"Handling AG": 0,
		"Traction": 7,
		"Mini-Turbo": 2
	},
	{
		"Name": "Roller",
		"Speed G": 0,
		"Speed W": 3,
		"Speed A": 3,
		"Speed AG": 0,
		"Acceleration": 6,
		"Weight": 0,
		"Handling G": 4,
		"Handling W": 4,
		"Handling A": 4,
		"Handling AG": 4,
		"Traction": 4,
		"Mini-Turbo": 6
	},
	{
		"Name": "Slim",
		"Speed G": 3,
		"Speed W": 2,
		"Speed A": 2,
		"Speed AG": 4,
		"Acceleration": 2,
		"Weight": 2,
		"Handling G": 4,
		"Handling W": 4,
		"Handling A": 4,
		"Handling AG": 3,
		"Traction": 1,
		"Mini-Turbo": 2
	},
	{
		"Name": "Slick",
		"Speed G": 4,
		"Speed W": 0,
		"Speed A": 0,
		"Speed AG": 4,
		"Acceleration": 1,
		"Weight": 3,
		"Handling G": 2,
		"Handling W": 0,
		"Handling A": 1,
		"Handling AG": 2,
		"Traction": 0,
		"Mini-Turbo": 0
	},
	{
		"Name": "Metal",
		"Speed G": 4,
		"Speed W": 3,
		"Speed A": 2,
		"Speed AG": 1,
		"Acceleration": 0,
		"Weight": 4,
		"Handling G": 2,
		"Handling W": 2,
		"Handling A": 0,
		"Handling AG": 1,
		"Traction": 2,
		"Mini-Turbo": 0
	},
	{
		"Name": "Button",
		"Speed G": 1,
		"Speed W": 2,
		"Speed A": 2,
		"Speed AG": 2,
		"Acceleration": 5,
		"Weight": 0,
		"Handling G": 3,
		"Handling W": 3,
		"Handling A": 2,
		"Handling AG": 4,
		"Traction": 3,
		"Mini-Turbo": 5
	},
	{
		"Name": "Off Road",
		"Speed G": 3,
		"Speed W": 4,
		"Speed A": 1,
		"Speed AG": 2,
		"Acceleration": 3,
		"Weight": 3,
		"Handling G": 1,
		"Handling W": 1,
		"Handling A": 2,
		"Handling AG": 2,
		"Traction": 6,
		"Mini-Turbo": 1
	},
	{
		"Name": "Sponge",
		"Speed G": 1,
		"Speed W": 1,
		"Speed A": 4,
		"Speed AG": 1,
		"Acceleration": 4,
		"Weight": 1,
		"Handling G": 2,
		"Handling W": 1,
		"Handling A": 3,
		"Handling AG": 2,
		"Traction": 6,
		"Mini-Turbo": 4
	}
];

const gliders = [{
		"Name": "Super Glider",
		"Speed G": 1,
		"Speed W": 1,
		"Speed A": 2,
		"Speed AG": 0,
		"Acceleration": 1,
		"Weight": 1,
		"Handling G": 1,
		"Handling W": 0,
		"Handling A": 1,
		"Handling AG": 1,
		"Traction": 1,
		"Mini-Turbo": 1
	},
	{
		"Name": "Parachute",
		"Speed G": 0,
		"Speed W": 1,
		"Speed A": 1,
		"Speed AG": 1,
		"Acceleration": 2,
		"Weight": 0,
		"Handling G": 1,
		"Handling W": 0,
		"Handling A": 2,
		"Handling AG": 1,
		"Traction": 1,
		"Mini-Turbo": 2
	},
	{
		"Name": "Plane Glider",
		"Speed G": 1,
		"Speed W": 0,
		"Speed A": 2,
		"Speed AG": 1,
		"Acceleration": 1,
		"Weight": 2,
		"Handling G": 1,
		"Handling W": 1,
		"Handling A": 1,
		"Handling AG": 0,
		"Traction": 0,
		"Mini-Turbo": 1
	},
	{
		"Name": "Parafoil",
		"Speed G": 0,
		"Speed W": 0,
		"Speed A": 1,
		"Speed AG": 1,
		"Acceleration": 2,
		"Weight": 1,
		"Handling G": 1,
		"Handling W": 1,
		"Handling A": 2,
		"Handling AG": 0,
		"Traction": 0,
		"Mini-Turbo": 2
	}
];

const initialKeys = [
	"Speed G",
	"Speed W",
	"Speed A",
	"Speed AG",
	"Acceleration",
	"Weight",
	"Handling G",
	"Handling W",
	"Handling A",
	"Handling AG",
	"Traction",
	"Mini-Turbo"
];

const priority = [
	"Handling A",
	"Handling W",
	"Handling AG",
	"Handling G",
	"Traction",
	"Mini-Turbo",
	"Speed A",
	"Speed W",
	"Speed G",
	"Speed AG",
	"Acceleration"
];

const combos = [];

for (d = 0; d < drivers.length; d++) {
	for (b = 0; b < bodies.length; b++) {
		for (t = 0; t < tires.length; t++) {
			for (g = 0; g < gliders.length; g++) {

				const driver = drivers[d];
				const body = bodies[b];
				const tire = tires[t];
				const glider = gliders[g];

				const combo = {
					"Driver": driver["Name"],
					"Body": body["Name"],
					"Tire": tire["Name"],
					"Glider": glider["Name"]
				}

				for (s = 0; s < initialKeys.length; s++) {
					const key = initialKeys[s];
					combo[key] = 3 + driver[key] + body[key] + tire[key] + glider[key];
				}

				combo["Inside Drift"] = body["Inside Drift"];

				combos.push(combo);
			}
		}
	}
}

for (i = 0; i < priority.length; i++) {
	const key = priority[i];
	const sort = (a, b) => b[key] - a[key];
	combos.sort(sort);
};

/*
require('fs').writeFile('./combos.js', JSON.stringify(combos),
	function (err) {
		if (err) {
			console.error('ERROR!');
		}
	}
);
*/