const drivers = [{
		"Name": "Baby-Peach",
		"Speed Ground": 0,
		"Speed Water": 0,
		"Speed Air": 0,
		"Speed AG": 0,
		"Accel": 4,
		"Weight": 0,
		"Handle Ground": 10,
		"Handle Water": 10,
		"Handle Air": 10,
		"Handle AG": 10,
		"Tract": 5,
		"Mini-Turbo": 5
	},
	{
		"Name": "Lemmy",
		"Speed Ground": 0,
		"Speed Water": 0,
		"Speed Air": 0,
		"Speed AG": 0,
		"Accel": 5,
		"Weight": 0,
		"Handle Ground": 9,
		"Handle Water": 9,
		"Handle Air": 9,
		"Handle AG": 9,
		"Tract": 3,
		"Mini-Turbo": 5
	},
	{
		"Name": "Dry-Bones",
		"Speed Ground": 1,
		"Speed Water": 1,
		"Speed Air": 1,
		"Speed AG": 1,
		"Accel": 5,
		"Weight": 1,
		"Handle Ground": 8,
		"Handle Water": 8,
		"Handle Air": 8,
		"Handle AG": 8,
		"Tract": 4,
		"Mini-Turbo": 4
	},
	{
		"Name": "Toadette",
		"Speed Ground": 2,
		"Speed Water": 2,
		"Speed Air": 2,
		"Speed AG": 2,
		"Accel": 5,
		"Weight": 2,
		"Handle Ground": 7,
		"Handle Water": 7,
		"Handle Air": 7,
		"Handle AG": 7,
		"Tract": 2,
		"Mini-Turbo": 4
	},
	{
		"Name": "Koopa",
		"Speed Ground": 2,
		"Speed Water": 2,
		"Speed Air": 2,
		"Speed AG": 2,
		"Accel": 4,
		"Weight": 2,
		"Handle Ground": 8,
		"Handle Water": 8,
		"Handle Air": 8,
		"Handle AG": 8,
		"Tract": 5,
		"Mini-Turbo": 4
	},
	{
		"Name": "Toad",
		"Speed Ground": 3,
		"Speed Water": 3,
		"Speed Air": 3,
		"Speed AG": 3,
		"Accel": 4,
		"Weight": 3,
		"Handle Ground": 7,
		"Handle Water": 7,
		"Handle Air": 7,
		"Handle AG": 7,
		"Tract": 4,
		"Mini-Turbo": 3
	},
	{
		"Name": "Inkling-Girl",
		"Speed Ground": 4,
		"Speed Water": 4,
		"Speed Air": 4,
		"Speed AG": 4,
		"Accel": 4,
		"Weight": 3,
		"Handle Ground": 6,
		"Handle Water": 6,
		"Handle Air": 6,
		"Handle AG": 6,
		"Tract": 3,
		"Mini-Turbo": 3
	},
	{
		"Name": "Peach",
		"Speed Ground": 5,
		"Speed Water": 5,
		"Speed Air": 5,
		"Speed AG": 5,
		"Accel": 3,
		"Weight": 4,
		"Handle Ground": 5,
		"Handle Water": 5,
		"Handle Air": 5,
		"Handle AG": 5,
		"Tract": 3,
		"Mini-Turbo": 3
	},
	{
		"Name": "Inkling-Boy",
		"Speed Ground": 5,
		"Speed Water": 5,
		"Speed Air": 5,
		"Speed AG": 5,
		"Accel": 3,
		"Weight": 5,
		"Handle Ground": 5,
		"Handle Water": 5,
		"Handle Air": 5,
		"Handle AG": 5,
		"Tract": 1,
		"Mini-Turbo": 3
	},
	{
		"Name": "Mario",
		"Speed Ground": 6,
		"Speed Water": 6,
		"Speed Air": 6,
		"Speed AG": 6,
		"Accel": 2,
		"Weight": 6,
		"Handle Ground": 4,
		"Handle Water": 4,
		"Handle Air": 4,
		"Handle AG": 4,
		"Tract": 2,
		"Mini-Turbo": 2
	},
	{
		"Name": "Luigi",
		"Speed Ground": 6,
		"Speed Water": 6,
		"Speed Air": 6,
		"Speed AG": 6,
		"Accel": 2,
		"Weight": 6,
		"Handle Ground": 5,
		"Handle Water": 5,
		"Handle Air": 5,
		"Handle AG": 5,
		"Tract": 1,
		"Mini-Turbo": 2
	},
	{
		"Name": "Metal-Mario",
		"Speed Ground": 8,
		"Speed Water": 8,
		"Speed Air": 8,
		"Speed AG": 8,
		"Accel": 1,
		"Weight": 10,
		"Handle Ground": 3,
		"Handle Water": 3,
		"Handle Air": 3,
		"Handle AG": 3,
		"Tract": 1,
		"Mini-Turbo": 1
	},
	{
		"Name": "Boo",
		"Speed Ground": 7,
		"Speed Water": 7,
		"Speed Air": 7,
		"Speed AG": 7,
		"Accel": 1,
		"Weight": 7,
		"Handle Ground": 3,
		"Handle Water": 3,
		"Handle Air": 3,
		"Handle AG": 3,
		"Tract": 3,
		"Mini-Turbo": 2
	},
	{
		"Name": "Donkey-Kong",
		"Speed Ground": 9,
		"Speed Water": 9,
		"Speed Air": 9,
		"Speed AG": 9,
		"Accel": 1,
		"Weight": 8,
		"Handle Ground": 2,
		"Handle Water": 2,
		"Handle Air": 2,
		"Handle AG": 2,
		"Tract": 0,
		"Mini-Turbo": 1
	},
	{
		"Name": "Wario",
		"Speed Ground": 10,
		"Speed Water": 10,
		"Speed Air": 10,
		"Speed AG": 10,
		"Accel": 0,
		"Weight": 9,
		"Handle Ground": 1,
		"Handle Water": 1,
		"Handle Air": 1,
		"Handle AG": 1,
		"Tract": 1,
		"Mini-Turbo": 0
	},
	{
		"Name": "Bowser",
		"Speed Ground": 10,
		"Speed Water": 10,
		"Speed Air": 10,
		"Speed AG": 10,
		"Accel": 0,
		"Weight": 10,
		"Handle Ground": 0,
		"Handle Water": 0,
		"Handle Air": 0,
		"Handle AG": 0,
		"Tract": 0,
		"Mini-Turbo": 0
	}
];

const bodies = [{
		"Name": "Standard Kart",
		"Speed Ground": 3,
		"Speed Water": 3,
		"Speed Air": 3,
		"Speed AG": 3,
		"Accel": 4,
		"Weight": 2,
		"Handle Ground": 3,
		"Handle Water": 2,
		"Handle Air": 3,
		"Handle AG": 3,
		"Tract": 3,
		"Mini-Turbo": 4,
		"Inside Drift": false
	},
	{
		"Name": "Varmit",
		"Speed Ground": 1,
		"Speed Water": 3,
		"Speed Air": 1,
		"Speed AG": 1,
		"Accel": 6,
		"Weight": 1,
		"Handle Ground": 5,
		"Handle Water": 4,
		"Handle Air": 2,
		"Handle AG": 4,
		"Tract": 4,
		"Mini-Turbo": 6,
		"Inside Drift": false
	},
	{
		"Name": "Mach 8",
		"Speed Ground": 3,
		"Speed Water": 3,
		"Speed Air": 4,
		"Speed AG": 5,
		"Accel": 3,
		"Weight": 3,
		"Handle Ground": 2,
		"Handle Water": 2,
		"Handle Air": 2,
		"Handle AG": 4,
		"Tract": 4,
		"Mini-Turbo": 4,
		"Inside Drift": false
	},
	{
		"Name": "Steel Diver",
		"Speed Ground": 4,
		"Speed Water": 5,
		"Speed Air": 0,
		"Speed AG": 2,
		"Accel": 1,
		"Weight": 4,
		"Handle Ground": 1,
		"Handle Water": 5,
		"Handle Air": 1,
		"Handle AG": 1,
		"Tract": 3,
		"Mini-Turbo": 2,
		"Inside Drift": false
	},
	{
		"Name": "Comet",
		"Speed Ground": 2,
		"Speed Water": 2,
		"Speed Air": 4,
		"Speed AG": 3,
		"Accel": 5,
		"Weight": 2,
		"Handle Ground": 4,
		"Handle Water": 2,
		"Handle Air": 4,
		"Handle AG": 3,
		"Tract": 3,
		"Mini-Turbo": 5,
		"Inside Drift": true
	},
	{
		"Name": "Teddy Buggy",
		"Speed Ground": 2,
		"Speed Water": 2,
		"Speed Air": 4,
		"Speed AG": 3,
		"Accel": 5,
		"Weight": 2,
		"Handle Ground": 4,
		"Handle Water": 2,
		"Handle Air": 4,
		"Handle AG": 3,
		"Tract": 3,
		"Mini-Turbo": 5,
		"Inside Drift": false
	},
	{
		"Name": "Circuit Special",
		"Speed Ground": 5,
		"Speed Water": 1,
		"Speed Air": 2,
		"Speed AG": 4,
		"Accel": 1,
		"Weight": 3,
		"Handle Ground": 1,
		"Handle Water": 1,
		"Handle Air": 0,
		"Handle AG": 2,
		"Tract": 1,
		"Mini-Turbo": 1,
		"Inside Drift": false
	},
	{
		"Name": "Standard ATV",
		"Speed Ground": 5,
		"Speed Water": 2,
		"Speed Air": 1,
		"Speed AG": 3,
		"Accel": 0,
		"Weight": 4,
		"Handle Ground": 0,
		"Handle Water": 1,
		"Handle Air": 0,
		"Handle AG": 1,
		"Tract": 5,
		"Mini-Turbo": 0,
		"Inside Drift": false
	},
	{
		"Name": "Jet Bike",
		"Speed Ground": 4,
		"Speed Water": 3,
		"Speed Air": 3,
		"Speed AG": 3,
		"Accel": 2,
		"Weight": 1,
		"Handle Ground": 3,
		"Handle Water": 3,
		"Handle Air": 3,
		"Handle AG": 2,
		"Tract": 2,
		"Mini-Turbo": 3,
		"Inside Drift": true
	},
	{
		"Name": "Prancer",
		"Speed Ground": 4,
		"Speed Water": 3,
		"Speed Air": 3,
		"Speed AG": 3,
		"Accel": 2,
		"Weight": 1,
		"Handle Ground": 3,
		"Handle Water": 3,
		"Handle Air": 3,
		"Handle AG": 2,
		"Tract": 2,
		"Mini-Turbo": 3,
		"Inside Drift": false
	},
	{
		"Name": "Mr. Scooty",
		"Speed Ground": 0,
		"Speed Water": 1,
		"Speed Air": 1,
		"Speed AG": 2,
		"Accel": 7,
		"Weight": 0,
		"Handle Ground": 5,
		"Handle Water": 4,
		"Handle Air": 4,
		"Handle AG": 5,
		"Tract": 4,
		"Mini-Turbo": 7,
		"Inside Drift": false
	},
	{
		"Name": "Streetle",
		"Speed Ground": 1,
		"Speed Water": 5,
		"Speed Air": 2,
		"Speed AG": 0,
		"Accel": 6,
		"Weight": 0,
		"Handle Ground": 4,
		"Handle Water": 5,
		"Handle Air": 3,
		"Handle AG": 2,
		"Tract": 6,
		"Mini-Turbo": 6,
		"Inside Drift": false
	},
	{
		"Name": "Master Cycle",
		"Speed Ground": 4,
		"Speed Water": 2,
		"Speed Air": 3,
		"Speed AG": 3,
		"Accel": 2,
		"Weight": 2,
		"Handle Ground": 3,
		"Handle Water": 2,
		"Handle Air": 2,
		"Handle AG": 3,
		"Tract": 0,
		"Mini-Turbo": 3,
		"Inside Drift": true
	},
	{
		"Name": "Sneeker",
		"Speed Ground": 4,
		"Speed Water": 2,
		"Speed Air": 3,
		"Speed AG": 3,
		"Accel": 2,
		"Weight": 2,
		"Handle Ground": 3,
		"Handle Water": 2,
		"Handle Air": 2,
		"Handle AG": 3,
		"Tract": 0,
		"Mini-Turbo": 3,
		"Inside Drift": false
	},
	{
		"Name": "Standard Bike",
		"Speed Ground": 2,
		"Speed Water": 2,
		"Speed Air": 3,
		"Speed AG": 4,
		"Accel": 5,
		"Weight": 1,
		"Handle Ground": 4,
		"Handle Water": 3,
		"Handle Air": 3,
		"Handle AG": 4,
		"Tract": 5,
		"Mini-Turbo": 5,
		"Inside Drift": false
	},
	{
		"Name": "Splat Buggy",
		"Speed Ground": 4,
		"Speed Water": 2,
		"Speed Air": 3,
		"Speed AG": 4,
		"Accel": 3,
		"Weight": 0,
		"Handle Ground": 2,
		"Handle Water": 3,
		"Handle Air": 1,
		"Handle AG": 5,
		"Tract": 3,
		"Mini-Turbo": 3,
		"Inside Drift": false
	},
	{
		"Name": "Master Cycle Zero",
		"Speed Ground": 2,
		"Speed Water": 4,
		"Speed Air": 3,
		"Speed AG": 3,
		"Accel": 2,
		"Weight": 3,
		"Handle Ground": 4,
		"Handle Water": 4,
		"Handle Air": 3,
		"Handle AG": 3,
		"Tract": 7,
		"Mini-Turbo": 3,
		"Inside Drift": false
	}
];

const tires = [{
		"Name": "Standard Tires",
		"Speed Ground": 2,
		"Speed Water": 3,
		"Speed Air": 3,
		"Speed AG": 2,
		"Accel": 4,
		"Weight": 2,
		"Handle Ground": 3,
		"Handle Water": 3,
		"Handle Air": 3,
		"Handle AG": 3,
		"Tract": 5,
		"Mini-Turbo": 3
	},
	{
		"Name": "Monster",
		"Speed Ground": 2,
		"Speed Water": 2,
		"Speed Air": 1,
		"Speed AG": 2,
		"Accel": 2,
		"Weight": 4,
		"Handle Ground": 0,
		"Handle Water": 1,
		"Handle Air": 1,
		"Handle AG": 0,
		"Tract": 7,
		"Mini-Turbo": 2
	},
	{
		"Name": "Roller",
		"Speed Ground": 0,
		"Speed Water": 3,
		"Speed Air": 3,
		"Speed AG": 0,
		"Accel": 6,
		"Weight": 0,
		"Handle Ground": 4,
		"Handle Water": 4,
		"Handle Air": 4,
		"Handle AG": 4,
		"Tract": 4,
		"Mini-Turbo": 6
	},
	{
		"Name": "Slim",
		"Speed Ground": 3,
		"Speed Water": 2,
		"Speed Air": 2,
		"Speed AG": 4,
		"Accel": 2,
		"Weight": 2,
		"Handle Ground": 4,
		"Handle Water": 4,
		"Handle Air": 4,
		"Handle AG": 3,
		"Tract": 1,
		"Mini-Turbo": 2
	},
	{
		"Name": "Slick",
		"Speed Ground": 4,
		"Speed Water": 0,
		"Speed Air": 0,
		"Speed AG": 4,
		"Accel": 1,
		"Weight": 3,
		"Handle Ground": 2,
		"Handle Water": 0,
		"Handle Air": 1,
		"Handle AG": 2,
		"Tract": 0,
		"Mini-Turbo": 0
	},
	{
		"Name": "Metal",
		"Speed Ground": 4,
		"Speed Water": 3,
		"Speed Air": 2,
		"Speed AG": 1,
		"Accel": 0,
		"Weight": 4,
		"Handle Ground": 2,
		"Handle Water": 2,
		"Handle Air": 0,
		"Handle AG": 1,
		"Tract": 2,
		"Mini-Turbo": 0
	},
	{
		"Name": "Button",
		"Speed Ground": 1,
		"Speed Water": 2,
		"Speed Air": 2,
		"Speed AG": 2,
		"Accel": 5,
		"Weight": 0,
		"Handle Ground": 3,
		"Handle Water": 3,
		"Handle Air": 2,
		"Handle AG": 4,
		"Tract": 3,
		"Mini-Turbo": 5
	},
	{
		"Name": "Off Road",
		"Speed Ground": 3,
		"Speed Water": 4,
		"Speed Air": 1,
		"Speed AG": 2,
		"Accel": 3,
		"Weight": 3,
		"Handle Ground": 1,
		"Handle Water": 1,
		"Handle Air": 2,
		"Handle AG": 2,
		"Tract": 6,
		"Mini-Turbo": 1
	},
	{
		"Name": "Sponge",
		"Speed Ground": 1,
		"Speed Water": 1,
		"Speed Air": 4,
		"Speed AG": 1,
		"Accel": 4,
		"Weight": 1,
		"Handle Ground": 2,
		"Handle Water": 1,
		"Handle Air": 3,
		"Handle AG": 2,
		"Tract": 6,
		"Mini-Turbo": 4
	}
];

const gliders = [{
		"Name": "Super Glider",
		"Speed Ground": 1,
		"Speed Water": 1,
		"Speed Air": 2,
		"Speed AG": 0,
		"Accel": 1,
		"Weight": 1,
		"Handle Ground": 1,
		"Handle Water": 0,
		"Handle Air": 1,
		"Handle AG": 1,
		"Tract": 1,
		"Mini-Turbo": 1
	},
	{
		"Name": "Parachute",
		"Speed Ground": 0,
		"Speed Water": 1,
		"Speed Air": 1,
		"Speed AG": 1,
		"Accel": 2,
		"Weight": 0,
		"Handle Ground": 1,
		"Handle Water": 0,
		"Handle Air": 2,
		"Handle AG": 1,
		"Tract": 1,
		"Mini-Turbo": 2
	},
	{
		"Name": "Plane Glider",
		"Speed Ground": 1,
		"Speed Water": 0,
		"Speed Air": 2,
		"Speed AG": 1,
		"Accel": 1,
		"Weight": 2,
		"Handle Ground": 1,
		"Handle Water": 1,
		"Handle Air": 1,
		"Handle AG": 0,
		"Tract": 0,
		"Mini-Turbo": 1
	},
	{
		"Name": "Parafoil",
		"Speed Ground": 0,
		"Speed Water": 0,
		"Speed Air": 1,
		"Speed AG": 1,
		"Accel": 2,
		"Weight": 1,
		"Handle Ground": 1,
		"Handle Water": 1,
		"Handle Air": 2,
		"Handle AG": 0,
		"Tract": 0,
		"Mini-Turbo": 2
	}
];

const stats = [
	"Speed Ground",
	"Speed Water",
	"Speed Air",
	"Speed AG",
	"Accel",
	"Weight",
	"Handle Ground",
	"Handle Water",
	"Handle Air",
	"Handle AG",
	"Tract",
	"Mini-Turbo"
];

const initialSort = [
	"Handle Air",
	"Handle Water",
	"Handle Ground",
	"Handle AG",
	"Tract",
	"Speed Air",
	"Speed Water",
	"Speed Ground",
	"Speed AG",
	"Accel",
	"Mini-Turbo"
];

const combos = [];

for (d = 0; d < drivers.length; d++) {
	for (b = 0; b < bodies.length; b++) {
		for (t = 0; t < tires.length; t++) {
			for (g = 0; g < gliders.length; g++) {

				const driver = drivers[d];
				const body = bodies[b];
				const tire = tires[t];
				const glider = gliders[g];

				const combo = {
					"Driver": driver["Name"],
					"Body": body["Name"],
					"Tire": tire["Name"],
					"Glider": glider["Name"]
				}

				for (s = 0; s < stats.length; s++) {
					const key = stats[s];
					combo[key] = 3 + driver[key] + body[key] + tire[key] + glider[key];
				}

				combo["Inside Drift"] = body["Inside Drift"];

				combos.push(combo);
			}
		}
	}
}

for (i = 0; i < initialSort.length; i++) {
	const key = initialSort[i];
	const sort = (a, b) => b[key] - a[key];
	combos.sort(sort);
};
/*
require('fs').writeFile('./combos.json', JSON.stringify(combos),
	function (err) {
		if (err) {
			console.error('ERROR!');
		}
	}
);
*/